require "jruby-parser"
require "pathname"
require "jruby-parser.jar"

import org.jrubyparser.util.diff.NodeDiff

class RubyDiff
  attr_accessor :file_one, :file_two, :node_diff


  #
  # Create a RubyDiff object which will create diff of two source
  # files based on AST generated by JRubyParser.
  #
  # @param  file_one [String] The path to the first source file.
  # @param  file_two [String] The path to the second source file.
  #
  # @return [RubyDiff] A Ruby object which holds a reference to a diff.
  def initialize(file_one, file_two)
    @file_one = file_one
    @file_two = file_two
    @node_diff = diff()
  end

  def read(file_name)
    path = Pathname.new(file_name).expand_path
    if path.exist?
      File.read path
    end
  end

  def parse(code_to_parse, file_name)
    JRubyParser.parse(code_to_parse, { :filename => file_name })
  end

  def diff()
    code_one = read(@file_one)
    code_two = read(@file_two)
    nodeA = parse(code_one, @file_one)
    nodeB = parse(code_two, @file_two)
    nd = org.jrubyparser.util.diff.NodeDiff.new(nodeA, code_one, nodeB, code_two)
    nd.deep_diff
  end
end

